version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    command: mongod --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
  server:
    container_name: server
    restart: always
    build:
      context: ./server/
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    links:
      - mongodb
  client:
    container_name: client
    build:
      context: ./client/
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - '80:80'
    links:
      - server
